#include "aluminumfalkon.h"

tap_dance_action_t tap_dance_actions[] = {
  [TD_ANGLE_CLOSE]        = ACTION_TAP_DANCE_DOUBLE(KC_LT, KC_GT),
  [TD_PARENTHESIS_CLOSE]  = ACTION_TAP_DANCE_DOUBLE(KC_LPRN, KC_RPRN),
  [TD_BRACKET_CLOSE]      = ACTION_TAP_DANCE_DOUBLE(KC_LBRC, KC_RBRC),
  [TD_BRACE_CLOSE]        = ACTION_TAP_DANCE_DOUBLE(KC_LCBR, KC_RCBR),
  [TD_WIN_Q_LALT_F4]      = ACTION_TAP_DANCE_DOUBLE(KC_Q, A(KC_F4)),
  [TD_OSX_Q_LGUI_Q]       = ACTION_TAP_DANCE_DOUBLE(KC_Q, LGUI(KC_Q)),
};